name: beaver_demo
description: Demo project for beaver-ci.
version: 0.1.0
author: Fluidic Team <dev@fluidic.io>
#homepage: https://www.example.com

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  beaver_demo_package_1:
    git: https://github.com/fluidic/beaver_demo_package_1.git
  beaver_demo_package_2:
    git: https://github.com/fluidic/beaver_demo_package_2.git
  beaver_demo_package_3:
    git: https://github.com/fluidic/beaver_demo_package_3.git

dev_dependencies:
  test: '>=0.12.0 <0.13.0'
