project_name: beaver_demo
description: "Demo project for beaver-ci."

# FIXME: Remove after implementing setup(init) command.
cloud_type: gcloud
zone: us-central1-a
cloud_project_name: beaver-ci

triggers:
  - url: "https://github.com/fluidic/beaver_demo"
    type: github
    events: ["github_event_push"]
    task:
      name: dart_package_test
      args: ["beaver_demo", "https://github.com/fluidic/beaver_demo", "trigger:head_commit.id"]
